### ISSUE TITLE
Установить SSL

### ISSUE THREAD

**Issue by RALMAZ** [RALMAZ/Pdd_bot#5]
Кажется это нужно для работы с api телеги

**Comment by ovan001** [comment]
Да, 

> All queries to the Telegram Bot API must be served over HTTPS and need to be presented in this form: https://api.telegram.org/bot<token>/METHOD_NAME. Like this for example:

**Comment by RALMAZ** [comment]
Ух ты а мой хостер умеет в автоматическое обновление серта ^_^

Запрос на установку сертификата Let's Encrypt добавлен 26.08.2017 11:38. 
Пожалуйста ожидайте. Изменения вступят в силу в течение 24 часов.

**Comment by RALMAZ** [comment]
This page is secure (valid HTTPS).

**Comment by RALMAZ** [comment]
Мой хостер заявляет что автоматически обновляет так что можно ложить болт
